### ISSUE TITLE
Why use cashedMnist?

### ISSUE THREAD

**Issue by Meric3** [vlukiyanov/pt-dec#24]
Hello vlukiyanov. 

First, thanks for your kind code. 
I just have a question about the dataset you implemented.
There are a lot of dataset classes for mnist using pytorch. 
But I don't see this style. I mean transform byte. 
Why you use this cachedMnist?

**Comment by vlukiyanov** [comment]
I think the transformations were meant to imitate the original DEC code

https://github.com/piiswrong/dec/blob/e551e01f90a3d67d2ef9c90e968c8faf5d8f857d/dec/dec.py#L373

I believe it should do something similar, but obviously a formal unit test would probably help here to make sure it matches the Caffe.

On the caching, thats just to speed it up.
