### ISSUE TITLE
Loss jumping up and down for pretain and fine tuning

### ISSUE THREAD

**Issue by saniazahan** [vlukiyanov/pt-dec#28]
Hi I am trying out your model with another dataset (NTU RGB-D 60) but the losses for pretain and fine tuning are acting weirdly. First they starts to decrease for some epochs then jumps up then starts decreasing again. This goes on for the entire epochs. I have changed optimizer from SGD to Adam.

**Comment by vlukiyanov** [comment]
Hi, thanks. This repo attempts to implement the algorithm as closely as possible to the DEC paper for the datasets in that paper (which I hope it does, if you find a bug please submit a PR). So my original aim wasn't to implement improvements that would deviate from that as from what I've seen applying this algorithm to other datasets is non-trivial, but if you want to submit a PR which provides options to change parameters that would be welcome.
