### ISSUE TITLE
accuracy is low

### ISSUE THREAD

**Issue by Deepayan137** [vlukiyanov/pt-dec#9]
Hi, I am getting an accuracy of 21% on MNSIT dataset after running your code. Is the problem with the code or there is something wrong with my implementation? Can you confirm that you are getting better accuracy with the same code?

**Comment by vlukiyanov** [comment]
I can verify this by pulling in the latest packages, looks like the DEC step is no longer functioning correctly and actually diverging; I'll check again with PyTorch 0.4.0 and 1.0.0 and see what has changed (a first guess was some option in KLDivLoss, but doesn't seem to be this). Can you paste the pip freeze/conda list --export of your virtual/conda environment? Thanks!

**Comment by vlukiyanov** [comment]
Was able to verify, not quite sure why the cluster assignment function was wrong, but it is now fixed; thanks for flagging up! I'll probably restructure the code a bit at some point as tracking down the error in model.py was quite meandering.
